version: "3.2"
services:
  mysqlmaster:
    image: bluffpointtech.com/bptmysql:1.0.0
    restart: always
    ports:
      - "3310:3306"
    volumes:
      - mysqlbptmaster:/var/lib/mysql
    networks:
      - mysqlinext
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    container_name: mysqlmaster

volumes:
  mysqlbptmaster:
networks:
  mysqlinext:
  